=== darellmusette/CanDar-website/About.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="schema1-about.xsd" namespace="http://www.w3.org/1999/xlink" />
  <xs:import schemaLocation="schema2-about.xsd" namespace="http://www.w3.org/1999/xhtml" />
  <xs:element name="About">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Aboutus">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element minOccurs="0" xmlns:q1="http://www.w3.org/1999/xhtml" ref="q1:html" />
              <xs:element minOccurs="0" name="Contactus">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="Facebook">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="Twitter">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="Instagram">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="Description1" type="xs:string" />
              <xs:element minOccurs="0" name="Description2" type="xs:string" />
              <xs:element minOccurs="0" name="Description3" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== darellmusette/CanDar-website/About.xml
<?xml version="1.0" encoding="UTF-8"?>
<About xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="About.xsd">
	<Aboutus>
		<Description1>
			About us
		</Description1>
		<Description2>
			Determination,power.
		</Description2>
		<Description3>
          We are two youngters actually studying at the University. We have decided to start-up our E-shopping system to provide others high quality services and products. Our objective is to ensure that our customers are satisfied with our products and services.
		</Description3>
	</Aboutus>

	<Aboutus xmlns:xlink="http://www.w3.org/1999/xlink">

		<Contactus xlink:type="simple" xlink:href="contact.xml">Click to get in contact with us!
		</Contactus>

		<Facebook xlink:type="simple" xlink:href="www.facebook.com">Click to discover our Facebook page!
		</Facebook>

		<Twitter xlink:type="simple" xlink:href="www.twitter.com">Click to discover our Twitter page!
		</Twitter>

		<Instagram xlink:type="simple" xlink:href="www.instagram.com">Click to discover our Instagram page!	
		</Instagram>
	</Aboutus>

	<Aboutus>
		<html xmlns="http://www.w3.org/1999/xhtml">
			<img src="basketimage4.jpg"/>
		</html>
	</Aboutus>
</About>
