=== darellmusette/CanDar-website/Contact.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="schema1.xsd" namespace="http://www.w3.org/1999/xlink" />
  <xs:element name="Contact">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="navbar">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Header" type="xs:string" />
              <xs:element name="Home">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Product">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="About">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Contact">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Service">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="body">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="box">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Email" type="xs:string" />
                    <xs:element name="Phone" type="xs:unsignedInt" />
                    <xs:element name="Location" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="footer-icon">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Facebook">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Twitter">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Instagram">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="footer-link">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Home">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="About">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Contact">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Service">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xlink:type" use="required" />
                      <xs:attribute ref="xlink:href" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="footer">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="copyright" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== darellmusette/CanDar-website/Contact.xml
<?xml version="1.0" encoding="UTF-8"?>

<Contact xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Contact.xsd">
	<navbar xmlns:xlink="http://www.w3.org/1999/xlink">
		<Header>CanDar Sports tech</Header>
		<Home xlink:type="simple" xlink:href="homepage.php">Click to return to home page!</Home>
		<Product xlink:type="simple" xlink:href="productpage.php">Click to view our products!</Product>
		<About xlink:type="simple" xlink:href="About.html">Click to view information about us!</About>
		<Contact xlink:type="simple" xlink:href="contact.php">Click to get in contact with us!</Contact>
		<Service xlink:type="simple" xlink:href="deliverypage.php">Click to view our services!</Service>
	</navbar>

	<body>
		<box>
			<Email>DarellMusette23@gmail.com</Email>
			<Phone>57488193</Phone>
			<Location>Mauritius</Location>
		</box>
	</body>

	<footer-icon xmlns:xlink="http://www.w3.org/1999/xlink">
		<Facebook xlink:type="simple" xlink:href="www.facebook.com">Click on the Facebook icon to view our page!
		</Facebook>

		<Twitter xlink:type="simple" xlink:href="www.twitter.com">
		Click on the Twitter icon to view our page!
		</Twitter>

		<Instagram xlink:type="simple" xlink:href="www.instagram.com">Click on the Instagram icon to view our page!	
		</Instagram>
	</footer-icon>

	<footer-link xmlns:xlink="http://www.w3.org/1999/xlink">
		<Home xlink:type="simple" xlink:href="homepage.php">Home</Home>
		<About xlink:type="simple" xlink:href="About.html">About</About>
		<Contact xlink:type="simple" xlink:href="contact.php">Contact</Contact>
		<Service xlink:type="simple" xlink:href="deliverypage.php">Services</Service>
	</footer-link>

	<footer>
		<copyright>copyright &#169;Sports Pro. All Rights Reserved</copyright>
		<!-- &#169 is the representation of the copyright symbol -->
	</footer>
</Contact>
