=== darellmusette/CanDar-website/register.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">

  <xs:simpleType name="fullname">
    <xs:restriction base="xs:string">
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Email">
    <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}"/>
    </xs:restriction>
</xs:simpleType>

  <xs:simpleType name="password">
    <xs:restriction base="xs:string">
      <xs:minLength value="5"/>
      <xs:maxLength value="8"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="Registrations">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="registration" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="fullname" type="fullname"/>
              <xs:element name="Email" type="Email"/>
              <xs:element name="password" type="password"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== darellmusette/CanDar-website/register.xml
<?xml version="1.0"?>
<Registrations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="register.xsd">
  <registration>
    <fullname>king</fullname>
    <Email>Darell@gmail.com</Email>
    <password>12345</password>
  </registration>
  <registration>
    <fullname>toma</fullname>
    <Email>toma@gmail.com</Email>
    <password>12345</password>
  </registration>
  <registration>
    <fullname>Rodney</fullname>
    <Email>Rodney@gmail.com</Email>
    <password>12345</password>
  </registration>
  <registration>
    <fullname>james</fullname>
    <Email>james@gmail.com</Email>
    <password>12345</password>
  </registration>
  <registration>
    <fullname>sky</fullname>
    <Email>sky@gmail.com</Email>
    <password>12345</password>
  </registration>
  <registration>
    <fullname>shane</fullname>
    <Email>shane@gmail.com</Email>
    <password>12345</password>
  </registration>
  <registration>
    <fullname>test</fullname>
    <Email>test@gmail.com</Email>
    <password>1234</password>
  </registration>
  <registration>
    <fullname>test</fullname>
    <Email>test@gmail.com</Email>
    <password>12345</password>
  </registration>
  <registration>
    <fullname></fullname>
    <Email></Email>
    <password></password>
  </registration>
</Registrations>
